### ISSUE TITLE
requiresAuth authentication requirements not met with errorOnRequiredAuth() returning true, calling next() with an Unauthorized error

### ISSUE THREAD

**Issue by n-sviridenko** [auth0/express-openid-connect#272]
### Describe the problem

I'm getting 401 when trying to login via auth0. While on auth0's end the login marked as successful:

<img width="1147" alt="Screenshot 2021-08-19 at 20 40 01" src="https://user-images.githubusercontent.com/9335422/130125832-dbe98635-1029-4014-9ba2-371344286212.png">

### What was the expected behavior?

Seeing my protected index page and focusing on more interesting stuff :-)

### Reproduction

- Upload the index function and the website files: `firebase deploy --only functions:index,hosting`
- Visit the website `/login` page
- Authorise the login via auth0 etc.
- You'll get `Unauthorized` after coming back to `/` of your website

```
2021-08-19T18:25:17.574269595Z D index: Function execution started
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT express:router dispatching GET /login
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT express:router query  : /login
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT express:router expressInit  : /login
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT express:router router  : /login
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT express:router dispatching GET /login
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT express:router <anonymous>  : /login
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT express:router <anonymous>  : /login
2021-08-19T18:25:17.598Z ? index: Thu, 19 Aug 2021 18:25:17 GMT body-parser:urlencoded skip empty body
2021-08-19T18:25:17.599Z ? index: 2021-08-19T18:25:17.598Z express-openid-connect:context req.oidc.login() called with returnTo: [REDACTED]
2021-08-19T18:25:17.600Z ? index: 2021-08-19T18:25:17.600Z express-openid-connect:getLoginState adding default state { returnTo: '[REDACTED]' }
2021-08-19T18:25:17.602Z ? index: 2021-08-19T18:25:17.601Z express-openid-connect:context redirecting to https://[REDACTED].eu.auth0.com/authorize?client_id=[REDACTED]&scope=openid%20profile%20email&response_type=id_token&redirect_uri=[REDACTED]&response_mode=form_post&nonce=[REDACTED]&state=[REDACTED]
2021-08-19T18:25:17.602Z ? index: 2021-08-19T18:25:17.602Z express-openid-connect:appSession session was deleted or is empty, clearing all matching session cookies
2021-08-19T18:25:17.603809474Z D index: Function execution took 30 ms, finished with status code: 302
2021-08-19T18:25:18.652103808Z D index: Function execution started
2021-08-19T18:25:18.657Z ? index: Thu, 19 Aug 2021 18:25:18 GMT express:router dispatching POST /callback
2021-08-19T18:25:18.657Z ? index: Thu, 19 Aug 2021 18:25:18 GMT express:router query  : /callback
2021-08-19T18:25:18.657Z ? index: Thu, 19 Aug 2021 18:25:18 GMT express:router expressInit  : /callback
2021-08-19T18:25:18.657Z ? index: Thu, 19 Aug 2021 18:25:18 GMT express:router router  : /callback
2021-08-19T18:25:18.657Z ? index: Thu, 19 Aug 2021 18:25:18 GMT express:router dispatching POST /callback
2021-08-19T18:25:18.657Z ? index: Thu, 19 Aug 2021 18:25:18 GMT express:router <anonymous>  : /callback
2021-08-19T18:25:18.658Z ? index: Thu, 19 Aug 2021 18:25:18 GMT express:router <anonymous>  : /callback
2021-08-19T18:25:18.658Z ? index: Thu, 19 Aug 2021 18:25:18 GMT body-parser:urlencoded body already parsed
2021-08-19T18:25:18.658Z ? index: 2021-08-19T18:25:18.658Z express-openid-connect:auth POST /callback called
2021-08-19T18:25:18.662Z ? index: 2021-08-19T18:25:18.662Z express-openid-connect:appSession found session, creating signed session cookie(s) with name 'appSession'(.i)
2021-08-19T18:25:18.663Z ? index: 2021-08-19T18:25:18.663Z express-openid-connect:appSession replacing chunked cookies with non chunked cookies
2021-08-19T18:25:18.663Z ? index: 2021-08-19T18:25:18.663Z express-openid-connect:appSession replacing chunked cookies with non chunked cookies
2021-08-19T18:25:18.664569509Z D index: Function execution took 13 ms, finished with status code: 302
2021-08-19T18:25:20.003019048Z D index: Function execution started
2021-08-19T18:25:20.007Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router dispatching GET /
2021-08-19T18:25:20.007Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router query  : /
2021-08-19T18:25:20.007Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router expressInit  : /
2021-08-19T18:25:20.007Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router router  : /
2021-08-19T18:25:20.007Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router dispatching GET /
2021-08-19T18:25:20.007Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router <anonymous>  : /
2021-08-19T18:25:20.008Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router <anonymous>  : /
2021-08-19T18:25:20.008Z ? index: Thu, 19 Aug 2021 18:25:20 GMT express:router bound requiresLoginMiddleware  : /
2021-08-19T18:25:20.008Z ? index: 2021-08-19T18:25:20.008Z express-openid-connect:requiresAuth authentication requirements not met with errorOnRequiredAuth() returning true, calling next() with an Unauthorized error
2021-08-19T18:25:20.008Z ? index: Thu, 19 Aug 2021 18:25:20 GMT finalhandler default 401
2021-08-19T18:25:20.009Z ? index: 2021-08-19T18:25:20.009Z express-openid-connect:appSession session was deleted or is empty, clearing all matching session cookies
2021-08-19T18:25:20.010Z ? index:     at /workspace/node_modules/express/lib/router/index.js:284:7
2021-08-19T18:25:20.010Z E index: UnauthorizedError: Authentication is required for this route.
    at requiresLoginMiddleware (/workspace/node_modules/express-openid-connect/middleware/requiresAuth.js:30:19)
    at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/workspace/node_modules/express/lib/router/index.js:317:13)
2021-08-19T18:25:20.010Z ? index:     at Function.process_params (/workspace/node_modules/express/lib/router/index.js:335:12)
2021-08-19T18:25:20.010Z ? index:     at next (/workspace/node_modules/express/lib/router/index.js:275:10)
2021-08-19T18:25:20.010Z ? index:     at /workspace/node_modules/express-openid-connect/middleware/auth.js:38:5
2021-08-19T18:25:20.010Z ? index:     at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
2021-08-19T18:25:20.010Z ? index:     at trim_prefix (/workspace/node_modules/express/lib/router/index.js:317:13)
2021-08-19T18:25:20.010Z ? index:     at /workspace/node_modules/express/lib/router/index.js:284:7
2021-08-19T18:25:20.011317122Z D index: Function execution took 9 ms, finished with status code: 401
```

**functions/firebase.json**

```json
{
  "hosting": {
    "target": "[REDACTED]",
    "public": "build",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "index"
      }
    ],
    "redirects": [
      {
        "source": "/non-index.html",
        "destination": "/",
        "type": 301
      }
    ]
  },
  "firestore": {
    "rules": "firestore.rules"
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    },
    "hosting": {
      "port": 5000
    },
    "pubsub": {
      "port": 8085
    },
    "ui": {
      "enabled": true
    }
  }
}
```

**functions/indexFunction.js** // Firebase HTTP function code (just a serverless function exposing an express server):

```js
const { auth } = require('express-openid-connect');
const admin = require('firebase-admin');
const fs = require('fs');
const path = require('path');
const functions = require('firebase-functions');
const express = require('express');
const reportError = require('./reportError');
const config = require('../config');

const app = express();
app.use(
  auth({
    secret: config.auth.secret, // a long string which is always same
    baseURL: config.auth.baseUrl, // url of the firebase app
    clientID: config.auth.clientId, // auth0 client id
    issuerBaseURL: config.auth.issuerBaseUrl, // https://[REDACTED].eu.auth0.com
    errorOnRequiredAuth: true, // otherwise I get infinite redirect
  }),
);

const tokenVarName = 'window.FIREBASE_TOKEN';

app.get('/', async (req, res) => {
  try {
    const firebaseToken = await admin.auth().createCustomToken(uid);
    let viewerHTML = fs
      .readFileSync(path.resolve(__dirname, 'non-index.html'))
      .toString();
    viewerHTML = viewerHTML.replace(
      `${tokenVarName};`,
      `${tokenVarName}=${JSON.stringify(firebaseToken)};`,
    );
    res.send(viewerHTML).end();
  } catch (e) {
    reportError(e);
    res.status(500).send();
  }
});

module.exports = functions.https.onRequest(app);
```

### Environment

- **Version of this library used:** `"express-openid-connect": "^2.5.0",`
- **Which framework are you using, if applicable:** `"express": "^4.17.1",` + firebase functions
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by n-sviridenko** [comment]
Recorded a quick screencast where I elaborate on this even more: https://www.loom.com/share/0ea91549d5c74bd6bc6502613ca7a69d

**Comment by n-sviridenko** [comment]
cc @adamjmcgrath

**Comment by n-sviridenko** [comment]
The Auth0 provider is google workspace

**Comment by adamjmcgrath** [comment]
Hi @n-sviridenko - thanks for sharing all these details.

From your logs it looks like the callback is successfully setting the `appSession` cookie in the callback handler `/callback`:

```
... D index: Function execution started
... express:router dispatching POST /callback
...
... express-openid-connect:appSession found session, creating signed session cookie(s) with name 'appSession'(.i)
...
... D index: Function execution took 13 ms, finished with status code: 302
```

But the `/` route that it gets redirected to isn't picking the cookie up

```
... D index: Function execution started
... express:router dispatching GET /
... express-openid-connect:requiresAuth authentication requirements not met with errorOnRequiredAuth() ...
... D index: Function execution took 9 ms, finished with status code: 401
```

Could you share what the cookies look like in the browser for the `/callback` and subsequent `/` request, eg

callback:
![image](https://user-images.githubusercontent.com/1299658/130444922-0d817417-e2a6-4f06-b039-c89b92eec013.png)

authenticated request after callback:
![image](https://user-images.githubusercontent.com/1299658/130444956-9f63e022-84d7-465b-bb78-f39083e89291.png)

I would expect to see an `appSession` cookie in "Response Cookies" of the `/callback` response and the same `appSession` cookie in the "Request Cookies" of the subsequent `/` request

**Comment by n-sviridenko** [comment]
@adamjmcgrath sure,

`/callback`:

<img width="845" alt="Screenshot 2021-08-28 at 20 17 02" src="https://user-images.githubusercontent.com/9335422/131227160-23b0db53-8cc6-4fc0-9a49-06c298d0524a.png">

`/`:

<img width="842" alt="Screenshot 2021-08-28 at 20 17 08" src="https://user-images.githubusercontent.com/9335422/131227162-09f7c343-7ae2-45c0-83bf-7e7d5a7fbb21.png">

**Comment by n-sviridenko** [comment]
I found the reason: https://firebase.google.com/docs/hosting/manage-cache#using_cookies

🥲

Thank you for guidance.

**Comment by adamjmcgrath** [comment]
No problem, thanks for the update @n-sviridenko
