### ISSUE TITLE
Error: Deriving bits failed

### ISSUE THREAD

**Issue by GlobalGamer2015** [auth0/express-openid-connect#284]
### Describe the problem

I was having certificate error with fetch so I looked into the issue, someone said it was fixed with Electron 15.1.0 so I updated Electron to that version, I then tried to start my App and had "Error: Deriving bits failed".
I looked into the code and disabled express-openid-connect and then I started running the app with no issues.

### What was the expected behavior?

No error about "deriving bits failed".

### Reproduction

- Step 1..
Install Electron 15.1.0 and Express-OpenID-Connect 2.5.1
- Step 2..
Run App.

### Environment

- **Version of this library used:** 2.5.1
- **Which framework are you using, if applicable:** Electron
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

Contact me on discord for a copy of the application. GG2015#8670

```
App threw an error during load
Error: Deriving bits failed
    at Object.hkdfSync (node:internal/crypto/hkdf:140:35)
    at module.exports.signing (C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\lib\hkdf.js:31:14)
    at C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\lib\transientHandler.js:58:29
    at Array.forEach (<anonymous>)
    at new TransientCookieHandler (C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\lib\transientHandler.js:57:13)
    at auth (C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\middleware\auth.js:30:21)
    at Object.<anonymous> (C:\Github\Odysee_Chatter_Bot_Client\src\index.js:119:15)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
Error: Deriving bits failed
    at Object.hkdfSync (node:internal/crypto/hkdf:140:35)
    at module.exports.signing (C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\lib\hkdf.js:31:14)
    at C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\lib\transientHandler.js:58:29
    at Array.forEach (<anonymous>)
    at new TransientCookieHandler (C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\lib\transientHandler.js:57:13)
    at auth (C:\Github\Odysee_Chatter_Bot_Client\src\node_modules\express-openid-connect\middleware\auth.js:30:21)
    at Object.<anonymous> (C:\Github\Odysee_Chatter_Bot_Client\src\index.js:119:15)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
```

**Comment by GlobalGamer2015** [comment]
Solved by using Electron 14.1.0
