### ISSUE TITLE
OPError errors handling

### ISSUE THREAD

**Issue by NiematojakTomasz** [auth0/express-openid-connect#296]
### Describe the problem you'd like to have solved

I am unable to handle invalidated token.
When I invalidate session at identity provider(keycloak) I am getting errors, that I am unable to handle using conventional approach, not I can find info in documentation on how to handle those:
```
OPError: invalid_grant (Session not active)
    at processResponse (D:\work\workspace\skill-matrix\skill-matrix-frontend\build\js\node_modules\openid-client\lib\helpers\process_response.js:45:13)
    at Client.grant (D:\work\workspace\skill-matrix\skill-matrix-frontend\build\js\node_modules\openid-client\lib\client.js:1249:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Client.refresh (D:\work\workspace\skill-matrix\skill-matrix-frontend\build\js\node_modules\openid-client\lib\client.js:995:22)
    at RequestContext.refresh (D:\work\workspace\skill-matrix\skill-matrix-frontend\build\js\node_modules\express-openid-connect\lib\context.js:30:23)
```

### Describe the ideal solution

Ability to add callback option that could redirect user or render custom page in such scenario.

### Additional information, if any

Tried (kotlin):
```kotlin
private fun authErrorHandler(
    err : dynamic,
    req : dynamic,
    res : dynamic,
    next : dynamic
) {
    err.printStackTrace()
    res.sendStatus(500)
}
//...
app.use(::authErrorHandler)
```

**Comment by adamjmcgrath** [comment]
Hi @NiematojakTomasz 

In Express you can write a custom error handler to catch this error, see https://expressjs.com/en/guide/error-handling.html#writing-error-handlers
