### ISSUE TITLE
Mismatch between types and implementation for transactionCookie

### ISSUE THREAD

**Issue by jeffrson** [auth0/express-openid-connect#334]
### Describe the problem

The new types (2.7.0) require `transactionCookie` inside `routes`: https://github.com/auth0/express-openid-connect/blob/master/index.d.ts#L441

However, in https://github.com/auth0/express-openid-connect/blob/master/lib/config.js#L83, transactionCookie is a top-level configuration, not contained in routes (https://github.com/auth0/express-openid-connect/blob/master/lib/config.js#L184), which leads to this error message:

TypeError: "routes.transactionCookie" is not allowed,
    at module.exports.get (/usr/src/app/.yarn/__virtual__/express-openid-connect-virtual-9917d258a9/0/cache/express-openid-connect-npm-2.7.0-b65e4d8088-0fc538a46b.zip/node_modules/express-openid-connect/lib/config.js:222:11),
    at auth (/usr/src/app/.yarn/__virtual__/express-openid-connect-virtual-9917d258a9/0/cache/express-openid-connect-npm-2.7.0-b65e4d8088-0fc538a46b.zip/node_modules/express-openid-connect/middleware/auth.js:28:18),

### What was the expected behavior?

Run, without error.

### Environment

- **Version of this library used:** 2.7.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by adamjmcgrath** [comment]
Thanks for raising - the types are wrong (the config is correct)

#335 should fix
