### ISSUE TITLE
TypeError: end_session_endpoint must be configured on the issuer

### ISSUE THREAD

**Issue by revenz** [auth0/express-openid-connect#342]
I'm receiving this error when logging out using google as an IDP

```
TypeError: end_session_endpoint must be configured on the issuer
    at assertIssuerConfiguration (/app/node_modules/openid-client/lib/helpers/assert.js:15:11)
    at Client.endSessionUrl (/app/node_modules/openid-client/lib/client.js:296:5)
    at ResponseContext.logout (/app/node_modules/express-openid-connect/lib/context.js:302:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

configuration is

```
        let authOptions = {
            authRequired: true,
            issuerBaseURL: oauth.IssuerBaseUrl, // https://accounts.google.com/
            clientID: oauth.ClientId, // my client id
            baseURL: oauth.BaseUrl, // my baseurl
            secret: oauth.Secret, // secret
            enableTelemetry: false,
            idpLogout: !!oauth.LogoutIdp, // set to false, same issue if set to true
            routes: {
                postLogoutRedirect:'/logged-out'
            }
        };
        app.use(
            auth(authOptions)
        );
```

Using auth0 it works fine, but some users want to use google, and I cannot get it to work on log out.  
I tried searching for that exact issue but nothing is coming up on google.

What am I doing wrong?

**Comment by revenz** [comment]
actually this only happened with idpLogout set to true.   closing as I can auto-set to false if matching google.
