### ISSUE TITLE
TypeError: r(...)(...).extend is not a function

### ISSUE THREAD

**Issue by chintsan** [auth0/express-openid-connect#425]
TIA.

I am getting subject error in lib/debug.js of express-openid-connect. 

stack trace as below. please let know how to proceed with this issue.

--------------------------
issue at lib/debug.js - require('debug')('express-openid-connect').extend(name);
                                             ^
TypeError: r(...)(...).extend is not a function
    at e.exports (....../dist/webpack:/move-dealer-webapp/server/node_modules/express-openid-connect/lib/debug.js:2:46)
    at Object.call (.../node_modules/express-openid-connect/middleware/auth.js:5:15)
    at Object.call (..../express-openid-connect/index.js:1:14)
    
   
  Using latest versions as below. 
    
    "express": "^4.18.2",
    "express-openid-connect": "^2.10.0",

**Comment by chintsan** [comment]
removing .extend(name) from  require('debug')('express-openid-connect').extend(name) is working. i am not sure why extend is causing a problem. 

do we need to install any dependancy related to extend ?

appreciate quick input on this.

**Comment by adamjmcgrath** [comment]
Hi @chintsan - could it be related to https://github.com/debug-js/debug/issues/643? What do you get when you do `npm ls debug`?

**Comment by adamjmcgrath** [comment]
> do we need to install any dependancy related to extend ?

No, debug comes with an extend method https://github.com/debug-js/debug/blob/4.3.4/src/common.js#L119

> does extend work in node js application only ?

This SDK only works in a node js application

**Comment by chintsan** [comment]
> npm ls debug

thank you @adamjmcgrath for reply. below is the output. 

i am seeing multiple and different versions of debug could that be a issue ? 

_i ran dedupe and then have shared the output_

─┬ @babel/core@7.17.8
│ └── debug@4.3.4
├─┬ @babel/preset-env@7.16.11
│ └─┬ babel-plugin-polyfill-corejs2@0.3.1
│   └─┬ @babel/helper-define-polyfill-provider@0.3.1
│     └── debug@4.3.3
├─┬ @babel/traverse@7.17.3
│ └── debug@4.3.4
├─┬ @move-core/stylelint-config-move@2.0.0
│ └─┬ stylelint@13.7.2
│   ├─┬ @stylelint/postcss-css-in-js@0.37.2
│   │ └─┬ @babel/core@7.12.3
│   │   └── debug@4.3.4
│   └── debug@4.3.3
├─┬ @move-ui/webpack@27.0.0
│ └─┬ postcss-color-function@4.1.0
│   └─┬ css-color-function@1.3.3
│     └── debug@3.2.6
├─┬ @sentry/cli@2.7.0
│ └─┬ https-proxy-agent@5.0.0
│   ├─┬ agent-base@6.0.2
│   │ └── debug@4.3.3
│   └── debug@4.3.3
├─┬ @typescript-eslint/eslint-plugin@5.4.0
│ └── debug@4.3.2
├─┬ @typescript-eslint/parser@5.4.0
│ ├─┬ @typescript-eslint/typescript-estree@5.4.0
│ │ └── debug@4.3.2
│ └── debug@4.3.2
├─┬ babel-jest@26.6.3
│ ├─┬ @jest/transform@26.6.2
│ │ └─┬ @babel/core@7.5.5
│ │   └── debug@4.3.4
│ ├─┬ babel-plugin-istanbul@6.0.0
│ │ └─┬ istanbul-lib-instrument@4.0.1
│ │   └─┬ @babel/core@7.12.9
│ │     └── debug@4.3.4
│ └─┬ babel-preset-jest@26.6.2
│   └─┬ babel-preset-current-node-syntax@1.0.0
│     └─┬ @babel/plugin-syntax-import-meta@7.10.4
│       └─┬ @babel/core@7.13.10
│         └── debug@4.3.4
├─┬ eslint-plugin-import@2.25.3
│ ├── debug@2.6.9
│ ├─┬ eslint-import-resolver-node@0.3.6
│ │ └── debug@3.2.7
│ └─┬ eslint-module-utils@2.7.1
│   └── debug@3.2.7
├─┬ eslint-plugin-monorepo@0.2.1
│ └─┬ eslint-module-utils@2.4.1
│   └── debug@2.6.9 deduped
├─┬ eslint-plugin-testing-library@3.10.1
│ └─┬ @typescript-eslint/experimental-utils@3.10.1
│   └─┬ @typescript-eslint/typescript-estree@3.10.1
│     └── debug@4.3.3
├─┬ eslint@7.32.0 invalid: "^5.16.0 || ^6.1.0" from node_modules/eslint-config-airbnb
│ ├─┬ @eslint/eslintrc@0.4.3
│ │ └── debug@4.3.3
│ ├─┬ @humanwhocodes/config-array@0.5.0
│ │ └── debug@4.3.3
│ └── debug@4.1.1
├─┬ jest-circus@26.6.3
│ └─┬ jest-runner@26.6.3
│   └─┬ jest-config@26.6.3
│     └─┬ @babel/core@7.5.5
│       └── debug@4.3.4
├─┬ jest@26.6.3
│ └─┬ @jest/core@26.6.3
│   └─┬ @jest/reporters@26.6.2
│     ├─┬ istanbul-lib-instrument@4.0.3
│     │ └─┬ @babel/core@7.12.9
│     │   └── debug@4.3.4
│     └─┬ istanbul-lib-source-maps@4.0.0
│       └── debug@4.3.3
├─┬ lerna@4.0.0
│ ├─┬ @lerna/add@4.0.0
│ │ └─┬ pacote@11.3.5
│ │   └─┬ npm-registry-fetch@11.0.0
│ │     └─┬ make-fetch-happen@9.1.0
│ │       └─┬ socks-proxy-agent@6.1.1
│ │         └── debug@4.3.1
│ └─┬ @lerna/publish@4.0.0
│   ├─┬ @lerna/npm-dist-tag@4.0.0
│   │ └─┬ npm-registry-fetch@9.0.0
│   │   └─┬ make-fetch-happen@8.0.14
│   │     └─┬ socks-proxy-agent@5.0.1
│   │       └── debug@4.3.3
│   └─┬ npm-registry-fetch@9.0.0
│     └─┬ make-fetch-happen@8.0.14
│       ├─┬ agentkeepalive@4.1.4
│       │ └── debug@4.3.4
│       ├─┬ http-proxy-agent@4.0.1
│       │ └── debug@4.3.3
│       └─┬ socks-proxy-agent@5.0.1
│         └── debug@4.3.3
├─┬ lint-staged@7.3.0
│ ├── debug@3.2.6
│ └─┬ micromatch@3.1.10
│   ├─┬ extglob@2.0.4
│   │ └─┬ expand-brackets@2.1.4
│   │   └── debug@2.6.9 deduped
│   └─┬ snapdragon@0.8.2
│     └── debug@2.6.9 deduped
├─┬ msw@0.31.0
│ └─┬ @mswjs/interceptors@0.11.1
│   └── debug@4.3.1
├─┬ needle@2.4.0 extraneous
│ └── debug@3.2.6 extraneous
├─┬ nodemon@1.19.1
│ ├── debug@3.2.6
│ └─┬ undefsafe@2.0.2
│   └── debug@2.6.9 deduped
├─┬ supertest@3.4.2
│ └─┬ superagent@3.8.3
│   └── debug@3.2.6
├─┬ testcafe@1.19.0
│ ├─┬ @babel/core@7.13.10
│ │ └── debug@4.3.4
│ ├─┬ @babel/plugin-transform-runtime@7.13.10
│ │ ├─┬ babel-plugin-polyfill-corejs2@0.1.10
│ │ │ ├─┬ @babel/core@7.13.10
│ │ │ │ └── debug@4.3.4
│ │ │ └─┬ @babel/helper-define-polyfill-provider@0.1.5
│ │ │   ├─┬ @babel/core@7.13.10
│ │ │   │ └── debug@4.3.4
│ │ │   ├─┬ @babel/helper-compilation-targets@7.16.7
│ │ │   │ └─┬ @babel/core@7.17.8
│ │ │   │   └── debug@4.3.4
│ │ │   └── debug@4.3.3
│ │ ├─┬ babel-plugin-polyfill-corejs3@0.1.7
│ │ │ └─┬ @babel/core@7.13.10
│ │ │   └── debug@4.3.4
│ │ └─┬ babel-plugin-polyfill-regenerator@0.1.6
│ │   └─┬ @babel/core@7.13.10
│ │     └── debug@4.3.4
│ ├─┬ @babel/preset-env@7.13.10
│ │ ├─┬ @babel/plugin-proposal-unicode-property-regex@7.12.13
│ │ │ └─┬ @babel/helper-create-regexp-features-plugin@7.12.17
│ │ │   └─┬ @babel/core@7.13.10
│ │ │     └── debug@4.3.4
│ │ └─┬ @babel/preset-modules@0.1.4
│ │   ├─┬ @babel/plugin-proposal-unicode-property-regex@7.16.7
│ │   │ └─┬ @babel/core@7.17.8
│ │   │   └── debug@4.3.4
│ │   └─┬ @babel/plugin-transform-dotall-regex@7.16.7
│ │     └─┬ @babel/core@7.17.8
│ │       └── debug@4.3.4 deduped
│ ├─┬ @babel/preset-react@7.12.13
│ │ └─┬ @babel/plugin-transform-react-jsx@7.12.17
│ │   └─┬ @babel/core@7.13.10
│ │     └── debug@4.3.4
│ ├── debug@4.3.1
│ ├─┬ testcafe-browser-tools@2.0.23
│ │ └── debug@4.3.1
│ ├─┬ testcafe-hammerhead@24.5.19
│ │ └── debug@4.3.1
│ └─┬ testcafe-legacy-api@5.1.4
│   └─┬ testcafe-hammerhead@24.5.23
│     └── debug@4.3.1
├─┬ webpack-bundle-analyzer@3.6.0
│ └─┬ express@4.17.1
│   ├─┬ body-parser@1.19.0
│   │ └── debug@2.6.9 deduped
│   ├── debug@2.6.9 deduped
│   ├─┬ finalhandler@1.1.2
│   │ └── debug@2.6.9 deduped
│   └─┬ send@0.17.1
│     └── debug@2.6.9 deduped
└─┬ webpack-dev-server@4.5.0
  ├─┬ compression@1.7.4
  │ └── debug@2.6.9 deduped
  ├─┬ http-proxy-middleware@2.0.1
  │ └─┬ http-proxy@1.18.1
  │   └─┬ follow-redirects@1.8.1
  │     └── debug@3.2.6
  ├─┬ portfinder@1.0.28
  │ └── debug@3.2.7
  ├─┬ serve-index@1.9.1
  │ └── debug@2.6.9 deduped
  └─┬ spdy@4.0.2
    ├── debug@4.3.4
    └─┬ spdy-transport@3.0.0
      └── debug@4.3.4

**Comment by chintsan** [comment]
> 



> > do we need to install any dependancy related to extend ?
> 
> No, debug comes with an extend method https://github.com/debug-js/debug/blob/4.3.4/src/common.js#L119
> 
> > does extend work in node js application only ?
> 
> This SDK only works in a node js application

I have installed this SDK in our backend only i.e in package.json of server where we start express server. 

but we have react at FE using webpack etc, so given this stack would this SDK work ?

**Comment by chintsan** [comment]
> > i am seeing multiple and different versions of debug could that be a issue ?
> 
> It shouldn't be - also I don't see this SDK listed in your dependencies?
> 

Below is the snapshot from the package.json, we are using as part of this SDK. 

extend and debug were explicitly added as was getting this issue. They are more or less redundant with regards to issue which persists with or without them. 

 "debug": "^4.3.4",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "express-http-context": "^1.2.4",
    "express-openid-connect": "auth0/express-openid-connect",
    "extend": "^3.0.2",
    "fs-extra": "^10",
    "got": "^11.8.2",
    "helmet": "^3.12.0",
    "hpagent": "^0.1.1",
    "http-proxy": "^1.18.1",
    "http-status-codes": "^2.1.4",
    "lodash": "^4.17.17",

**Comment by chintsan** [comment]
update - i had previously installed express-openid-connect only under server's package.json, explaining with project structure as below.

<root folder>

     <server>
      packaje.json - _had installed express-openid-connect etc here only_

package.json - **_Now when i installed  express-openid-connect in package.json of root folder its working._**

query - do we need to install express-openid-connect at root level's package.json ?

**Comment by adamjmcgrath** [comment]
> extend and debug were explicitly added as was getting this issue. They are more or less redundant with regards to issue which persists with or without them.

`extend` and `debug.extend` are 2 different things, so I wouldn't bother installing `extend`

> query - do we need to install express-openid-connect at root level's package.json ?

No, it should behave like any other npm package, as long as it's available when you do `require('...')` it should work as expected.

This seems like an issue with your webpack build, your monorepo setup and/or https://github.com/debug-js/debug/issues/643 - it's difficult to say without being able to reproduce it myself.

Also...

> "express-openid-connect": "auth0/express-openid-connect",

Any reason why you are installing this package from GitHub rather than the npm repository? You could also try changing this to `"express-openid-connect": "^2.10.0",` and doing a clean install.

**Comment by chintsan** [comment]
Any reason why you are installing this package from GitHub rather than the npm repository? You could also try changing this to "express-openid-connect": "^2.10.0", and doing a clean install.

yeh this was done.  thank you.
