### ISSUE TITLE
Deprecation warning (promisify) when upgrading to Node v21.6.0

### ISSUE THREAD

**Issue by Will956** [auth0/express-openid-connect#571]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello 👋 

We recently upgraded our Node service to v21.6.0 and we start to see some deprecation warning:

```
[DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
```

With `--trace-deprecation` argument, we can see those warnings come from the lib:
```
(node:45354) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
    at node:internal/util:431:17
    at new Promise (<anonymous>)
    at RedisStore.get (node:internal/util:416:12)
    at CustomStore.get (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express-openid-connect@2.17.1_express@4.18.2/node_modules/express-openid-connect/lib/appSession.js:203:19)
    at /REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express-openid-connect@2.17.1_express@4.18.2/node_modules/express-openid-connect/lib/appSession.js:325:46
    at /REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/dd-trace@4.23.0/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:22:57
    at /REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/dd-trace@4.23.0/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21
    at Layer.handle [as handle_request] (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:328:13)
    at /REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:346:12)
    at Function.process_params (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/dd-trace@4.23.0/node_modules/dd-trace/packages/datadog-instrumentations/src/express.js:70:23)
    at next (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:175:3)
    at router (/REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:47:12)
    at /REDACTED/REDACTED/REDACTED/REDACTED/apps/api-server/dist/main.js:587:14
```

This comes from this code https://github.com/auth0/express-openid-connect/blob/8ade66846a1f041591e267d2296b02df2604f1f4/lib/appSession.js#L190

### Reproduction

Tested in the express-opend-id-connect sample app:
```js
const dotenv = require("dotenv");
const express = require("express");
const http = require("http");
const logger = require("morgan");
const path = require("path");
const router = require("./routes/index");
const { auth } = require("express-openid-connect");

// Redis store
const { createClient } = require("redis");
const RedisStore = require("connect-redis").default;
let redisClient = createClient();
redisClient.connect().catch(console.error);

dotenv.load();

const app = express();

app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");

app.use(logger("dev"));
app.use(express.static(path.join(__dirname, "public")));
app.use(express.json());

const config = {
  authRequired: false,
  auth0Logout: true,
  session: {
    store: new RedisStore({ client: redisClient }),
  },
};

(...)
```

<img width="879" alt="Capture d’écran 2024-01-17 à 21 36 43" src="https://github.com/auth0/express-openid-connect/assets/13664270/06d59fc2-8782-4580-ae1a-763eebf2194d">

### express-openid-connect version

2.17.1

### Express version

4.18.2

### Node.js version

21.6.0

**Comment by natlibfi-jonollil** [comment]
There is no Deprecation warning in documentation
https://nodejs.org/api/util.html#utilpromisifyoriginal

**Comment by chrisvander** [comment]
Is this package maintained?

**Comment by gyaneshgouraw-okta** [comment]
Hey @chrisvander  and @Will956 ,
Apologies for the delay in addressing this issue.
We’re prioritising it now and will work on getting it fixed as soon as possible. I’ll keep you updated with any progress along the way.
Thanks for your patience!

**Comment by Will956** [comment]
Hello @gyaneshgouraw-okta, do you have any updates on this? Thanks!

**Comment by Will956** [comment]
`"connect-redis": "8.1.0",` this one

**Comment by Will956** [comment]
When we encountered this issue, it was `"connect-redis": "7.1.0",` - maybe that's what you're are looking for

**Comment by redoper1** [comment]
@kushalshit27 After upgrading to the latest version, we’re encountering a `TypeError: callback is not a function` when reading the current session using connect-mssql-v2@5.2.1 as the session store:

`'TypeError: callback is not a function
    at MSSQLStore.get (***/node_modules/connect-mssql-v2/dist/src/store.js:196:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ***/node_modules/express-openid-connect/lib/appSession.js:327:29'`

It seems that express-openid-connect is calling store.get() without a callback as second arg, but connect-mssql-v2 requires it.
