### ISSUE TITLE
option sameSite is invalid

### ISSUE THREAD

**Issue by bryceroney** [auth0/express-openid-connect#92]
### Description
I am receiving the following error when using this library in conjunction with the Auth0 guide:

```
TypeError: option sameSite is invalid
    at Object.serialize (/home/bryce/wslcode/.../node_modules/cookie/index.js:174:15)
    at ServerResponse.res.cookie (/home/bryce/wslcode/.../node_modules/express/lib/response.js:853:36)
    at Object.store (/home/bryce/wslcode/.../node_modules/express-openid-connect/lib/transientHandler.js:32:7)
    at ResponseContext.login (/home/bryce/wslcode/.../node_modules/express-openid-connect/lib/context.js:91:26)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
```
I have tried to work out where the error is coming from but can't quite see how it's occurring.

### Environment
My config:
```
const config = {
  required: false,
  auth0Logout: true,
  appSession: {
    secret: process.env.APP_SECRET,
  },
  baseURL: process.env.BASE_URL,
  clientID: process.env.AUTH0_CLIENT_ID,
  issuerBaseURL: process.env.AUTH0_HOST,
};
```

> Please provide the following:

- **Version of this library used:** 1.0.1
- **Version of the platform or framework used, if applicable:** Node 12

**Comment by bryceroney** [comment]
Update: I just realised I was running an old version of express with an old dependency on the cookie library.
